# Generated by Django 4.1 on 2024-09-27 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TypKaroserie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('karoserie', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='ZnackyAut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('znacka', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Inzerat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('popis', models.CharField(max_length=128)),
                ('vykon', models.CharField(max_length=128)),
                ('rok_vyroby', models.PositiveIntegerField(max_length=4)),
                ('cena', models.PositiveIntegerField()),
                ('datum_pridani', models.DateTimeField()),
                ('vytvoreno', models.DateTimeField(auto_now_add=True)),
                ('karoserie', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='viewer.typkaroserie')),
                ('znacka', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='viewer.znackyaut')),
            ],
        ),
    ]
