# Generated by Django 4.1 on 2024-09-27 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inzerat',
            name='pocet_zobrazeni',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
