# Generated by Django 4.1 on 2024-09-27 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0002_inzerat_pocet_zobrazeni'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Inzerat',
            new_name='Inzeraty',
        ),
    ]
