# Generated by Django 4.1 on 2024-09-29 11:50

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0004_komentare'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='komentare',
            name='Inzeraty',
        ),
        migrations.AlterField(
            model_name='inzeraty',
            name='datum_pridani',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='inzeraty',
            name='rok_vyroby',
            field=models.PositiveIntegerField(),
        ),
        migrations.AddField(
            model_name='komentare',
            name='inzeraty',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='komentare_set', to='viewer.inzeraty'),
            preserve_default=False,
        ),
    ]
